title:            Mind the Cloud Podcast
description:      "The podcast about the developers and companies using the cloud to create the future"
logo:             site-logo.png
disqus_shortname: mindthecloud
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
# url:              http://localhost:4000

# Owner/author information
owner:
  name:           "Danilo Sato and Rafael Rosa"
  avatar:         bio-photo.jpg
  email:          contact@mindthecloud.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        _MindTheCloud
  facebook:
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# iTunes specific configs
itunes_summary: "Mind the Cloud, the podcast about the developers and companies using the cloud to create the future."
itunes_url: https://itunes.apple.com/us/podcast/mind-the-cloud-podcast/id951036809
base_url: http://mindthecloud.com

# Analytics and webmaster tools stuff goes here
google_analytics: UA-7340111-3
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Danilo Sato
    url: /dtsato/
  - title: Rafael Rosa Fu
    url: /rafaelrosafu/

future:      true
highlighter: pygments
markdown:    kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor", "bin"]
